# Default values for powerfulseal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
powerfulseal:
  image:
    repository: bloomberg/powerfulseal
    imagePullPolicy: Always
    tag: 3.0.1

  policies: |
    config:
      runStrategy:
        minSecondsBetweenRuns: 30
        maxSecondsBetweenRuns: 300
    scenarios: []

  args:
  - --no-cloud
