# the service account to read from all namespaces
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}

# cluster role to read things and delete pods in all namespaces
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-clusterrole
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - namespaces
  - deployments
  - services
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
    - customresourcedefinitions
  verbs:
  - get
  - list
- apiGroups:
  - "powerfulseal.io"
  resources:
  - scenarios
  verbs:
  - get
  - list
# bind the cluster role to the service account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-{{ .Chart.Name }}-serviceaccount
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ .Chart.Name }}-clusterrole
